# Generated by Django 4.0 on 2021-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debet', models.BooleanField()),
                ('credit', models.BooleanField()),
                ('category', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
