# Generated by Django 4.0 on 2021-12-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
