# Generated by Django 4.0 on 2021-12-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alter_transaction_credit_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='credit', max_length=100),
        ),
    ]
