# Generated by Django 4.0 on 2021-12-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debet', 'debet'), ('credit', 'credit')], default='credit', max_length=6),
        ),
    ]
